version: "3.5"
networks:
  traefik_proxy:
    external: true
  docker_subnet:
    external: true
secrets:
  rt_token:
    file: ${SECRETS_DIR}/rt_token
  rt_masters:
    file: ${SECRETS_DIR}/rt_masters
services:
  rutorrent-flood:
    image: romancin/rutorrent-flood:latest
    container_name: rutorrent-flood
    deploy:
      resources:
        limits:
          cpus: "4.00"
          memory: 4G
        reservations:
          cpus: "2.00"
          memory: 2G
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    security_opt:
      - seccomp="/etc/docker/seccomp/default.json"
      - no-new-privileges
    # Disables the user namespace for this container.
    userns_mode: "host"
    restart: on-failure:5
    # If user namespaces is enabled, disable 'domainname' to avoid
    # permission errors.
    domainname: ${INTERNAL_DOMAIN}
    hostname: rutorrent-flood
    networks:
      traefik_proxy:
      docker_subnet:
        # Configure static IP for container. This makes rTorrent available
        # outside of internal network using port forwarding in firewall.
        ipv4_address: ${RTORRENT_IP}
    volumes:
      - ${DOCKER_DIR}/rutorrent-flood/config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${MEDIA_DIR}:/media
    environment:
      - PUID=${UID}
      - PGID=${DOWNLOADS_GID}
      - TZ=${TZ}
      - FILE__RT_TOKEN=/run/secrets/rt_token
      - FILE__RT_MASTERS=/run/secrets/rt_masters
    secrets:
      - rt_token
      - rt_masters
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      # HTTP router - 'rutorrent-rtr'.
      - "traefik.http.routers.rutorrent-rtr.entrypoints=https"
      - "traefik.http.routers.rutorrent-rtr.rule=Host(`rutorrent.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.rutorrent-rtr.tls=true"
      # HTTP service - 'rutorrent-svc'.
      - "traefik.http.routers.rutorrent-rtr.service=rutorrent-svc"
      # Force Traefik to use https over port 443.
      - "traefik.http.services.rutorrent-svc.loadbalancer.server.scheme=https"
      - "traefik.http.services.rutorrent-svc.loadbalancer.server.port=443"
      # HTTP router - 'flood-rtr'.
      - "traefik.http.routers.flood-rtr.entrypoints=https"
      - "traefik.http.routers.flood-rtr.rule=Host(`flood.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.flood-rtr.tls=true"
      # HTTP service - 'flood-svc'.
      - "traefik.http.routers.flood-rtr.service=flood-svc"
      - "traefik.http.services.flood-svc.loadbalancer.server.port=3000"
      # Middlewares
      - "traefik.http.routers.rutorrent-rtr.middlewares=chain-no-auth@file"     # No authentication.
      #- "traefik.http.routers.rutorrent-rtr.middlewares=chain-basic-auth@file" # Basic authentication.
