# This configuration file is for Traefik v1 and not actively maintained.

# Configure log level. Can be any of the following:
#  - DEBUG
#  - INFO
#  - WARN
#  - ERROR
#  - FATAL
#  - PANIC
logLevel = "INFO"

# Configure default entry points.
defaultEntryPoints = ["http", "https"]
# Fixes issues with i.e. Nextcloud..
InsecureSkipVerify = true

# Configure Traefik API/Dashboard.
[api]
  dashboard = true
  entrypoint = "dashboard"

# Configure connection to Docker host system.
[docker]
  # Do not use Docker daemon socket.
  #endpoint = "unix:///var/run/docker.sock"
  # Connect to Docker daemon using TCP.
  endpoint = "tcp://chost.$INTERNAL_DOMAIN:2376"
  domain = "$INTERNAL_DOMAIN"
  watch = true
  # Hide all Docker containers that do not have the 'traefik.enable=true'
  # labet set.
  exposedbydefault = false

# Enable Docker over TLS.
[docker.tls]
  ca = "/certs/docker/ca.pem"
  cert = "/certs/docker/cert.pem"
  key = "/certs/docker/key.pem"
  insecureSkipVerify = false

# Configure entry points and re-direct to HTTPS.
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

  # Configure entry point for Traefik API/Dashboard with basic authentication.
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        usersFile = "/secret/.htpasswd"

# Configure Let's Encrypt (ACME) certificate authority.
[acme]
  email = "$CF_API_EMAIL"
  storage="/certs/acme/acme.json"
  entryPoint = "https"
  acmeLogging = true
  # Use ACME staging. Remove comment to use stage servers.
  #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 300
[[acme.domains]]
   main = "*.$EXTERNAL_DOMAIN"
[[acme.domains]]
   main = "*.$INTERNAL_DOMAIN"
