version: "3.5"
networks:
  traefik_proxy:
    external: true
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/24
services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 2G
        reservations:
          cpus: "1.00"
          memory: 1G
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    security_opt:
      - seccomp="/etc/docker/seccomp/default.json"
      - no-new-privileges
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    # Disables the user namespace for this container.
    userns_mode: "host"
    restart: on-failure:5
    # If user namespaces is enabled, disable 'domainname' to avoid
    # permission errors.
    domainname: ${EXTERNAL_DOMAIN}
    hostname: nextcloud
    networks:
      - traefik_proxy
      - internal
    volumes:
      - ${DOCKER_DIR}/nextcloud/config:/config
      - ${DOCKER_DIR}/nextcloud/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.frontend.rule=Host:nextcloud.${EXTERNAL_DOMAIN}"
      - "traefik.port=443"
      - "traefik.protocol=https"
      - "traefik.docker.network=traefik_proxy"
      # Sets the max-age of the STS header.
      - "traefik.frontend.headers.STSSeconds=315360000"
      # Adds the IncludeSubdomains section of the STS header.
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      # Adds the preload flag to the STS header.
      - "traefik.frontend.headers.STSPreload=true"
      # Adds the STS header.
      - "traefik.frontend.headers.forceSTSHeader=true"
      # Forces the frontend to redirect to SSL if a non-SSL request is sent.
      - "traefik.frontend.headers.SSLRedirect=true"
      # This setting configures the hostname that redirects will be based on.
      - "traefik.frontend.headers.SSLHost=${EXTERNAL_DOMAIN}"
      # Adds the X-Frame-Options header with the value of DENY.
      - "traefik.frontend.headers.frameDeny=true"
      # Overrides the X-Frame-Options header with the custom value.
      - "traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN"
      # Adds the X-XSS-Protection header with the value 1; mode=block.
      - "traefik.frontend.headers.browserXSSFilter=true"
      # Adds the X-Content-Type-Options header with the value nosniff.
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.redirect.permanent=true"
      - "traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/"
  nextcloud-db:
    image: linuxserver/mariadb:latest
    container_name: nextcloud-db
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 1G
        reservations:
          cpus: "1.00"
          memory: 512M
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - seccomp="/etc/docker/seccomp/default.json"
      - no-new-privileges
    # Disables the user namespace for this container.
    userns_mode: "host"
    restart: on-failure:5
    hostname: nextcloud-db
    networks:
      - internal
    volumes:
      - ${DOCKER_DIR}/nextcloud/db:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
        reservations:
          cpus: "0.50"
          memory: 256M
    cap_drop:
      - ALL
    security_opt:
      - seccomp="/etc/docker/seccomp/default.json"
      - no-new-privileges
    # Disables the user namespace for this container.
    userns_mode: "host"
    user: "1002:1002"
    restart: on-failure:5
    hostname: nextcloud-redis
    networks:
      - internal
    read_only: true
    volumes:
      - ${DOCKER_DIR}/nextcloud/redis:/data
    sysctls:
      # Fix warning message according to the following reported issue:
      # https://github.com/docker-library/redis/issues/35
      net.core.somaxconn: "511"