# This Docker Compose file is for Traefik v1 and is not actively maintained.
version: "3.5"
networks:
  traefik_proxy:
    external: true
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.2.0/24
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 256M
        reservations:
          cpus: "0.50"
          memory: 128M
    cap_drop:
      - ALL
    security_opt:
      - seccomp="/etc/docker/seccomp/default.json"
      - no-new-privileges
    restart: on-failure:5
    # If user namespaces is enabled, disable 'domainname' to avoid
    # permission errors.
    #domainname: ${INTERNAL_DOMAIN}
    hostname: portainer
    networks:
      - traefik_proxy
      - internal
    read_only: true
    volumes:
      - ${DOCKER_DIR}/portainer/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.${INTERNAL_DOMAIN}"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_proxy"
      # Sets the max-age of the STS header.
      - "traefik.frontend.headers.STSSeconds=315360000"
      # Adds the IncludeSubdomains section of the STS header.
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      # Adds the preload flag to the STS header.
      - "traefik.frontend.headers.STSPreload=true"
      # Adds the STS header.
      - "traefik.frontend.headers.forceSTSHeader=true"
      # Forces the frontend to redirect to SSL if a non-SSL request is sent.
      - "traefik.frontend.headers.SSLRedirect=true"
      # This setting configures the hostname that redirects will be based on.
      - "traefik.frontend.headers.SSLHost=${INTERNAL_DOMAIN}"
      # Adds the X-Frame-Options header with the value of DENY.
      #- "traefik.frontend.headers.frameDeny=true" # Security header option 'customFrameOptionsValue' overrides this.
      # Overrides the X-Frame-Options header with the custom value.
      - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:${INTERNAL_DOMAIN}"
      # Adds the X-XSS-Protection header with the value 1; mode=block.
      - "traefik.frontend.headers.browserXSSFilter=true"
      # Adds the X-Content-Type-Options header with the value nosniff.
      - "traefik.frontend.headers.contentTypeNosniff=true"
